name: Hexo Blog CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: macOS-10.14

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: "14.x"

      - name: Setup Hexo Dependencies
        run: |
          npm install -g hexo-cli
          npm install -g yuque-hexo
          npm install -g gulp
          npm install
      - name: Setup Deploy Private Key
        env:
          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts  
      - name: Setup Git Infomation
        run: |
          git config --global user.name '${{ secrets.USER_NAME }}'
          git config --global user.email '${{ secrets.USER_EMAIL }}'
      - name: Deploy Hexo
        run: |
          rm -rf source/photos/*.json
          node photos/tool.js
          hexo clean
          yuque-hexo clean
          YUQUE_TOKEN=${{ secrets.HEXO_YUQUE_TOKEN }} yuque-hexo sync
          hexo bangumi -d
          hexo bangumi -u
          hexo generate
          gulp
          hexo deploy